### POST PRODUCT - 상품 등록
POST http://localhost:8080/api/products
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJvd25lcjEiLCJ0eXBlIjoiYWNjZXNzIiwiYXV0aCI6IlJPTEVfT1dORVIiLCJleHAiOjE3MzE1MDQ5NzQsImlhdCI6MTczMTUwMzE3NH0.DJysEkBe0gkBu3pxp1TvTThjvaOdTq4YwYYicF83HJs
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="storeId"

f47c1f3b-89bb-4f7d-b380-b8e1a3e05d77
--boundary
Content-Disposition: form-data; name="productName"

비빔메밀면 샐러드
--boundary
Content-Disposition: form-data; name="productDescription"

매콤새콤달콤한 고추장비빔 드레싱과 닭가슴살, 메밀면 등 토핑들이 조화롭게 어우러진 비빔면 스타일의 K-BIBIM 샐러드
--boundary
Content-Disposition: form-data; name="price"

17500
--boundary
Content-Disposition: form-data; name="stockQuantity"

50
--boundary
Content-Disposition: form-data; name="maxOrderLimit"

4
--boundary
Content-Disposition: form-data; name="displayStatus"

PENDING_SALE
--boundary
Content-Disposition: form-data; name="isHidden"

false
--boundary
Content-Disposition: form-data; name="primaryImageIndex"

1
--boundary
Content-Disposition: form-data; name="files[]"; filename="profile.png"
Content-Type: image/png

< C:\Users\misu\Downloads\profile.png
--boundary
Content-Disposition: form-data; name="files[]"; filename="icon-todo.png"
Content-Type: image/png

< C:\Users\misu\Downloads\icon-todo.png


### PATCH PRODUCT IMAGE - 상품이미지 수정 및 관리
PATCH http://localhost:8080/api/products/d246d5a0-cc19-4495-bd37-932d56447989/images
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJvd25lcjEiLCJ0eXBlIjoiYWNjZXNzIiwiYXV0aCI6IlJPTEVfT1dORVIiLCJleHAiOjE3MzE1MDE4ODMsImlhdCI6MTczMTUwMDA4M30.kd14lyBOOzGi0v6jLmklRB3vbOziFg-koyDoFQLchaE
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="primaryImageIndex"

1
--boundary
Content-Disposition: form-data; name="deletedImageIds[]"

8cc1bf9b-2f4a-47e6-885b-152c4ffe17c7
--boundary
Content-Disposition: form-data; name="deletedImageIds[]"

15895e6a-6837-47cd-8065-003ed922005e
--boundary
Content-Disposition: form-data; name="files[]"; filename="F0e_tTIaQAAPSli.png"
Content-Type: image/png

< C:\Users\misu\Downloads\F0e_tTIaQAAPSli.png
--boundary
Content-Disposition: form-data; name="files[]"; filename="jjal.jpg"
Content-Type: image/jpg

< C:\Users\misu\Downloads\jjal.jpg
--boundary
Content-Disposition: form-data; name="files[]"; filename="icon-todo.png"
Content-Type: image/png

< C:\Users\misu\Downloads\icon-todo.png